### ISSUE TITLE
Nothing shows?!

### ISSUE THREAD

**Issue by htilly** [retroflex/MMM-Skola24#1]
Installed the module according to the readme but nothings shows :/ 

The log simply says:
mm | [18.08.2022 09:52.40.405] [LOG]   Connecting socket for: MMM-Skola24

The config is straight out of the example:
{
        module: 'MMM-Skola24',
        header: 'My Timetable',
        position: 'bottom_right',
        config: {
                host: 'goteborg.skola24.se',
                unitGuid: 'ODJiYjcwYjEtYWE3MS1mNGU1LWFhNDktOTU2ZDM5M2M4NmQ5',
                selection: 'OGQ5ZmM5YTQtOTZkMi1mY2I4LWE4M2ItZTJiZjI5MjFiMmEx',
        }
},

Also found my own schedule, but same issue. Nothing is being rendered on the screen. 

How can I debug further?

I set the loglevel to:
logLevel: ["INFO", "LOG", "WARN", "ERROR", "DEBUG"],

**Comment by retroflex** [comment]
@htilly I disabled it on my mirror during the summer, so I haven't tested it lately (in case there were changes in the API, which is unlikely though).

But have you checked that the schedule is available here?
https://web.skola24.se/timetable/timetable-viewer/goteborg.skola24.se/any-test

For example my kids' school haven't published the new schedules yet.

Also can you check the log in the browser?
