### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by andzie82** [retroflex/MMM-Skola24#2]
I get this error in Chrome dev mode when i use the module,

TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at updateModuleContent (main.js:215:21)
    at main.js:142:5
    at new Promise (<anonymous>)
    at updateDomWithContent (main.js:140:10)
    at main.js:122:28

Something i can fix on my side?

**Comment by retroflex** [comment]
@andzie82 I missed your issue and didn't see it until now. Did you find out what the problem was? It has worked fine for me until a while back when I suddenly started getting the same message and no output. Not sure what has changed.

**Comment by dskhokho** [comment]
I am having the same issue. Great module though, would be fantastic to have it working again...

**Comment by retroflex** [comment]
@andzie82 @dskhokho I think it should work now if you do an update.

**Comment by dskhokho** [comment]
Fantastic, seems to work like a charm but will only know for sure next week due to w.44 being off I guess. Thank you so much!

**Comment by retroflex** [comment]
Yeah, I noticed that as well and haven't tested on more busy weeks, so let's hope it works.

**Comment by dskhokho** [comment]
I seem to be stuck on “Laddar…”

Is it just me?

From: Johan ***@***.***>
Date: Thursday, 2 November 2023 at 18:33
To: retroflex/MMM-Skola24 ***@***.***>
Cc: Daniel Nordstrom ***@***.***>, Mention ***@***.***>
Subject: Re: [retroflex/MMM-Skola24] Type error (Issue #2)

Yeah, I noticed that as well and haven't tested on more busy weeks, so let's hope it works.

**Comment by retroflex** [comment]
@dskhokho No, I had the same, so I just pushed a fix. Seems the API needed a new value for some reason. So to fix you need to update, then also add the "schoolYear" value to your config. See the updated readme.

**Comment by dskhokho** [comment]
Superstar! Works like a charm, much appreciated!

From: Johan ***@***.***>
Date: Sunday, 5 November 2023 at 21:51
To: retroflex/MMM-Skola24 ***@***.***>
Cc: Daniel Nordstrom ***@***.***>, Mention ***@***.***>
Subject: Re: [retroflex/MMM-Skola24] Type error (Issue #2)

@dskhokho<https://github.com/dskhokho> No, I had the same, so I just pushed a fix. Seems the API needed a new value for some reason. So to fix you need to update, then also add the "schoolYear" value to your config. See the updated readme.
